# Generated by Django 4.1.2 on 2022-10-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount',
            new_name='price',
        ),
    ]
