# Generated by Django 4.1.2 on 2022-11-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_rename_discount_offer_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
